export const ALL_TOURS_BEGIN = 'ALL_TOURS_BEGIN';
export const SINGLE_TOUR_BEGIN = 'SINGLE_TOUR_BEGIN';
export const GET_SINGLE_TOUR_SUCCESS = 'GET_SINGLE_TOUR_SUCCESS';
export const GET_ALL_TOURS_SUCCESS = 'GET_ALL_TOURS_SUCCESS';
